detector:
  evt_subsample_fac: 1
  buffer_size_s: 30.0
  tsteps_per_msg: 8
  msg_per_window: 60
  centroid_find_window: 7
  centroid_find_thresh: 5
  triangulation_sv_thresh: 0.01
  min_baseline_dist: 0.5
  max_reproj_err_px: 6
  dist_thresh:
    min: 0.0
    max: 50.0

hough1:
  window_size: 200
  threshold: 20
  nms_radius: 10
  radial_resolution: 260
  angular_resolution: 21
  angle_range:
    min: -10
    max: 10

tracker:
  linearity_window: 7
  linearity_tol_px: 3

tracker_mgr:
  centr_buffer_l: 200
  spawn_thresh: 40
  dxdt_cluster_tol_px: 6
  max_dx_allowed: 100
  dxdt_range:
    min: 50.0
    max: 5000.0
  maturity_age: 1.0

output:
  map_file: ""
  rviz: true
